image: docker:latest
services: 
  - docker:19.03-dind

stages: 
  - build
  - deploy

build-prod:
  stage: build
  before_script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker login -u $DOCKER_LOGIN -p $DOCKER_TOKEN

  script:
    - docker build --tag $CI_REGISTRY_IMAGE:prod .
    - docker push $CI_REGISTRY_IMAGE:prod
  only:
    - master


deploy-prod:
  stage: deploy
  before_script:
    - "which ssh-agent || ( apk update && apk add openssh-client bash curl)"
    - mkdir -p ~/.ssh
    - eval $(ssh-agent -s)
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  script:
    - bash -c "ssh-add <(echo \"$SSH_PRIVATE_KEY_PROD\")"
    - export COMPOSE_HTTP_TIMEOUT=200
    - ssh root@$HOST_PROD "docker-compose -f ~/docker-compose.yml down --remove-orphans"
    - ssh root@$HOST_PROD "docker-compose -f ~/docker-compose.yml pull"
    - ssh root@$HOST_PROD "docker-compose -f ~/docker-compose.yml up -d"
  only:
    - master

# deploy-staging:
#   stage: deploy
#   before_script:
#     - "which ssh-agent || ( apk update && apk add openssh-client bash curl)"
#     - mkdir -p ~/.ssh
#     - eval $(ssh-agent -s)
#     - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
#   script:
#     - bash -c "ssh-add <(echo \"$SSH_PRIVATE_KEY\")"
#     - export COMPOSE_HTTP_TIMEOUT=200
#     - ssh root@$HOST_PROD "docker-compose -f ~/prospectix-api.yml down --remove-orphans"
#     - ssh root@$HOST_PROD "docker-compose -f ~/prospectix-api.yml pull"
#     - ssh root@$HOST_PROD "docker-compose -f ~/prospectix-api.yml up -d"
#   only:
#     - staging