image: docker:19.03.0
services: 
  - docker:19.03-dind

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: "/certs"

stages: 
  - build
  - deploy

build:
  stage: build
  before_script:
      - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
      - docker login -u $DOCKER_LOGIN -p $DOCKER_TOKEN
  script:
      - echo $CI_REGISTRY_IMAGE
      - docker build --tag $CI_REGISTRY_IMAGE:prod
  only:
    - master

deploy:
    stage: deploy
    before_script:
        - "which ssh-agent || ( apk update && apk add openssh-client bash curl)"
        - mkdir -p ~/.ssh
        - eval $(ssh-agent -s)
        - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    script:
        - bash -c "ssh-add <(echo \"$SSH_PRIVATE_KEY\")"
        - export COMPOSE_HTTP_TIMEOUT=200
        - ssh root@$HOST_PROD "docker-compose -f ~/prospectix-api.yml down --remove-orphans"
        - ssh root@$HOST_PROD "docker-compose -f ~/prospectix-api.yml pull"
        - ssh root@$HOST_PROD "docker-compose -f ~/prospectix-api.yml up -d"
    only:
        - master